### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by afknapping** [samuelayo/getting_started_with_vuex#1]
Just wanted to let you that this was really helpful in getting vuex running 🙏

I even managed to extend it with delete and restore functions: https://github.com/filtercake/piggyback (it's not on the screenshot, but if you run it there is a tab with the todo example)

great work! 👍

**Comment by samuelayo** [comment]
Thank you very much for the feedback, I appreciate.

i'll also be sure to look at your repo.

Regards,
Samuel
